import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "I knew this would happen",
  description: "Generated by create next app",
};

// app/layout.tsx
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-black flex justify-center overflow-x-hidden">
        
        {/* bg-[#1D1D33] 클래스를 반드시 추가해야 합니다! */}
        <div className="w-full max-w-md min-h-[100dvh] bg-[#1D1D33] shadow-2xl relative flex flex-col">
          {children}
        </div>

      </body>
    </html>
  );
}